# Generated by Django 3.2.9 on 2021-12-01 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='curiosities',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='curiosities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curiosity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curiosities')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('curiosity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curiosities')),
            ],
        ),
    ]
