# Generated by Django 3.1.5 on 2021-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curiosities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('curiosity', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
