# Generated by Django 3.2.9 on 2021-12-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211201_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curiosities',
            old_name='curiosity',
            new_name='text',
        ),
    ]
