# Generated by Django 3.2.9 on 2021-12-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_curiosity_curiosities_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='curiosities',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
