# Generated by Django 3.2.9 on 2021-12-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_curiosities_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curiosities',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
