# Generated by Django 3.2.9 on 2021-12-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
